# Generated by Django 4.1.5 on 2023-03-06 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meet", "0003_meetingpost_place_meetingpost_place_lat_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="meetingpost",
            name="status",
            field=models.CharField(
                choices=[("success", "모집중"), ("warning", "모집종료")],
                default="success",
                max_length=20,
            ),
        ),
    ]
