# Generated by Django 4.1.5 on 2023-03-06 08:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("meet", "0004_alter_meetingpost_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="meetingpost",
            name="is_attendance",
            field=models.ManyToManyField(
                blank=True,
                related_name="attendance_meet_set",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
