# Generated by Django 4.1.5 on 2023-02-15 05:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("post", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="post",
            options={"ordering": ["-id"]},
        ),
        migrations.AddField(
            model_name="post",
            name="like_user_set",
            field=models.ManyToManyField(
                blank=True, related_name="like_post_set", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
