# Generated by Django 4.1.5 on 2023-03-01 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0003_comment"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="comment",
            options={"ordering": ["-id"]},
        ),
    ]
